#!/usr/bin/env php
<?php

use PhpLang\Phack;

$program = array_shift($_SERVER['argv']);
$ast = false;
$infile = array_shift($_SERVER['argv']);
if ($infile === '--ast') {
    $ast = true;
    $infile = array_shift($_SERVER['argv']);
}
if ($infile === '-') {
    $infile = 'php://stdin';
}

if ($infile === null) {
    fwrite(STDERR, "Usage: [--ast] {$program} filename.php\n\n");
    fwrite(STDERR, "Transpile filename.php from HackLang to PHP\n");
    fwrite(STDERR, "or dump AST when --ast passed\n");
    exit;
}

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    throw new \RuntimeException("Unable to locate vendor/autoload.php");
}

$file = file_get_contents($infile);
if ($ast) {
    print_r(Phack\compileString($file));
} else {
    echo "<?php", PHP_EOL, Phack\transpileString($file),PHP_EOL;
}
