#!/usr/bin/env php
<?php

use PhpLang\Phack;

if (empty($_SERVER['argv'][1])) {
    fwrite(STDERR, "Usage: {$_SERVER['argv'][0]} filename.php\n\n");
    fwrite(STDERR, "Transpile filename.php from HackLang to PHP");
    exit;
}

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    throw new \RuntimeException("Unable to locate vendor/autoload.php");
}

if ($_SERVER['argv'][1] === '-') {
  $file = stream_get_contents(STDIN);
} else {
  $file = file_get_contents($_SERVER['argv'][1]);
}

if (!strncmp($file, '<?hh', 4)) {
    $file = "<?php".PHP_EOL.Phack\transpileString($file);
}
echo $file . PHP_EOL;
